# Generated by Django 5.2.8 on 2026-07-27 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='reopened_at',
            field=models.DateTimeField(blank=True, help_text="Set when a mistakenly-resolved message is reopened. resolved_at/resolved_by are deliberately NOT cleared when this happens -- kept as a historical record of what happened, same reasoning as staff_notes.StaffNote's restore fields.", null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='reopened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages_reopened', to=settings.AUTH_USER_MODEL),
        ),
    ]
