# Generated by Django 5.2.8 on 2026-07-21 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('category', models.CharField(db_index=True, max_length=30)),
                ('event_type', models.CharField(db_index=True, help_text="Machine-readable event identifier, e.g. 'ENQUIRY_SUBMITTED'. Domain-specific vocabulary belongs in the calling app (e.g. admissions/services.py), not here.", max_length=50)),
                ('title', models.CharField(help_text='Feature 1: Event Title.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Feature 1: Event Description.')),
                ('actor_role', models.CharField(blank=True, help_text="Free-text snapshot of the actor's role at event time, same pattern as communication.Message.sender_role / staff_notes.StaffNote.author_role.", max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('icon', models.CharField(blank=True, help_text="Icon identifier -- a lucide-react icon name (e.g. 'file-plus', 'send', 'check-circle'), rendered directly by templates/timeline/_timeline_list.html.", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Null for system-generated events with no human actor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_entries', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id', 'created_at'], name='timeline_ti_content_a6695d_idx'), models.Index(fields=['content_type', 'object_id', 'category'], name='timeline_ti_content_147f84_idx')],
            },
        ),
    ]
