# Generated by Django 5.2.8 on 2026-07-23 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courses', '0001_initial'),
        ('timeline', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineentry',
            name='college',
            field=models.ForeignKey(blank=True, help_text="Phase 3C, Feature 4 (College Isolation): a real FK -- not resolved through content_object -- for efficient college-scoped admin queries, the same reasoning audit.AuditLog already uses. Optional and generic: only the calling code (which knows what obj is) can supply it; TimelineService itself has no idea what 'college' means for any given object type. SET_NULL, not CASCADE, so a college's own removal never takes its timeline history down with it.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_entries', to='courses.college'),
        ),
        migrations.AddIndex(
            model_name='timelineentry',
            index=models.Index(fields=['college', 'created_at'], name='timeline_ti_college_c4d249_idx'),
        ),
    ]
