# Generated by Django 5.2.8 on 2026-07-19 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(help_text="Short reason, e.g. 'Incorrect phone number' or 'Re-upload Class XII marksheet'.", max_length=255)),
                ('message', models.TextField(blank=True, help_text='Optional extra detail shown to the student.')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESPONDED', 'Responded'), ('RESOLVED', 'Resolved')], db_index=True, default='OPEN', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, help_text='Set when the student saves an edit while this request is open.', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_requests', to='admissions.enquiry')),
                ('requested_by', models.ForeignKey(help_text='The staff member who asked for the correction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correction_requests_made', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, help_text='The staff member who reviewed and closed this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correction_requests_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['enquiry', 'status'], name='admissions__enquiry_3f18a3_idx')],
            },
        ),
    ]
