# Generated by Django 5.2.8 on 2026-07-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(help_text="Full display name of the course, e.g. 'B.Tech Computer Science'.", max_length=150, unique=True)),
                ('duration', models.CharField(help_text="Human-readable duration, e.g. '4 Years' or '18 Months'.", max_length=50)),
                ('eligibility', models.CharField(help_text='Minimum eligibility criteria for admission to this course.', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive courses are hidden from the public site but preserved for historical enquiries.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['course_name'],
            },
        ),
    ]
