# Generated by Django 5.2.8 on 2026-08-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadparticipant',
            name='last_read_at',
            field=models.DateTimeField(blank=True, help_text="When THIS participant last read the thread. Bugfix: Message.is_read/read_at (below) is a single flag shared by the whole thread -- correct for a 2-party thread, but wrong the moment a third participant exists (e.g. Platform Admin + College Admin + College Staff all following one Enquiry): the first of them to open it silently marked the message read for the other two as well, even though they'd never seen it. Per-viewer 'unread' is now always computed by comparing a message's created_at against the CURRENT viewer's own last_read_at here (see CommunicationService.get_unread_message_ids), never against the shared Message.is_read flag. NULL means this participant has never marked the thread read -- treated as 'everything not sent by them is unread'.", null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False, help_text="Aggregate 'has at least one other participant read this yet' signal, used only for the sender's own Sent/Read receipt display. NOT per-viewer unread state -- see ThreadParticipant.last_read_at for that; a 3+-participant thread cannot be represented by a single thread-wide flag."),
        ),
    ]
