# Generated by Django 5.2.8 on 2026-07-22 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(db_index=True, help_text="Action Name -- machine-readable, e.g. 'ENQUIRY_STATUS_CHANGED'.", max_length=100)),
                ('action_category', models.CharField(blank=True, db_index=True, help_text="Feature 2 grouping (e.g. 'Authentication', 'Admission', 'College Management'). Plain text, not a choices enum -- 'future modules should easily register new actions' without a migration, same reasoning as timeline.TimelineEntry.category.", max_length=50)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, default='INFO', max_length=10)),
                ('event_source', models.CharField(blank=True, db_index=True, help_text="Feature 4, e.g. 'Web', 'Admin Panel', 'API', 'System', 'Background Job'. Plain text for the same forward-compatibility reason as action_category.", max_length=30)),
                ('actor_role', models.CharField(blank=True, max_length=50)),
                ('target_model', models.CharField(blank=True, help_text="e.g. 'admissions.Enquiry' -- a plain label, deliberately not a ContentType FK. See module docstring.", max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('object_display_name', models.CharField(blank=True, max_length=255)),
                ('previous_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('snapshot_data', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, help_text='Null for system/background-job-generated entries.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('college', models.ForeignKey(blank=True, help_text="A real FK (not a snapshot string) for efficient college-scoped querying (Feature 9) -- SET_NULL, not CASCADE, so a college's own removal can never take its audit history down with it.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='courses.college')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='audit_audit_created_2c1626_idx'), models.Index(fields=['action_category', 'created_at'], name='audit_audit_action__900390_idx'), models.Index(fields=['college', 'created_at'], name='audit_audit_college_335559_idx'), models.Index(fields=['target_model', 'object_id'], name='audit_audit_target__114c40_idx'), models.Index(fields=['severity', 'created_at'], name='audit_audit_severit_effc12_idx')],
            },
        ),
    ]
