# Generated by Django 5.2.8 on 2026-08-02 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(db_index=True, help_text="Machine-readable event identifier, e.g. 'STAFF_REPLIED', 'ENQUIRY_ADMITTED'. Deliberately a plain CharField, not choices= — same reasoning as timeline.TimelineEntry.event_type — so future modules add new notification types without a migration.", max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('body', models.CharField(blank=True, max_length=500)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High')], default='NORMAL', max_length=10)),
                ('action_url', models.CharField(blank=True, help_text='Precomputed deep-link (e.g. the enquiry detail page), supplied by the caller who already knows what kind of object this is about — avoids teaching this app owner-type-dispatch logic the way dashboard.views._thread_owner_detail_url needed for Communication.', max_length=500)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('college', models.ForeignKey(blank=True, help_text="Optional, caller-supplied — same reasoning as timeline.TimelineEntry.college / audit.AuditLog.college — for efficient college-scoped queries later. This app has no idea what 'college' means for any given object type; only the calling code does. SET_NULL, not CASCADE, so a college's own removal never takes a user's notification history down with it.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='courses.college')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', 'created_at'], name='notificatio_recipie_86ea8b_idx'), models.Index(fields=['content_type', 'object_id'], name='notificatio_content_702c56_idx')],
            },
        ),
    ]
